### ISSUE TITLE
toggle dark/light mode

### ISSUE THREAD

**Issue by black-arm** [DevLeonardoCommunity/github-stats#55] opened 2023-09-04 20:03 UTC
### Describe the feature

We can create a button for change theme from dark to light. 

## It should be implemented because...
the user chooses his favorite theme

## Additional context

- [X] I have used the search function to check if an issue already exists
- [x] I'd like to work on this issue

**Comment by Balastrong** [comment] 2023-09-05 12:17
Good idea, go for it! :)

**Comment by CBID2** [comment] 2024-01-29 21:10
Can I work on this @Balastrong? It's been 5 months since it was assigned

**Comment by Balastrong** [comment] 2024-01-29 21:18
We do have a theme selector now, the issue is probably already completed but if you see some room for improvement it's welcome :D

**Comment by CBID2** [comment] 2024-01-29 21:44
> We do have a theme selector now, the issue is probably already completed but if you see some room for improvement it's welcome :D
> 
> Otherwise I think we can close this one ;)

Ok

**Comment by CBID2** [comment] 2024-01-29 21:45
> We do have a theme selector now, the issue is probably already completed but if you see some room for improvement it's welcome :D
> 
> Otherwise I think we can close this one ;)

You can close it

**Closed** 2024-01-29 21:48 UTC
Labels: enhancement
